spring:
  application:
    name: graze
  datasource:
    url: jdbc:postgresql://localhost:5433/graze
    username: graze_user
    password: graze_password
  flyway:
    enabled: true
    schemas: graze
    default-schema: graze
    create-schemas: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: graze
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
