spring:
  application:
    name: graze
  datasource:
    url: jdbc:postgresql://localhost:5433/graze
    username: graze_user
    password: graze_password
  flyway:
    enabled: true
    schemas: graze
    default-schema: graze
    create-schemas: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: graze
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/graze-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/graze-realm/protocol/openid-connect/certs}

graze:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
  keycloak:
    client-id: ${KEYCLOAK_CLIENT_ID:graze-app}
    admin-server-url: ${KEYCLOAK_ADMIN_SERVER_URL:http://localhost:8180}
    realm: ${KEYCLOAK_REALM:graze-realm}
    admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}   # override in production via env var
    admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}   # override in production via env var

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.springframework.security: INFO

