services:
  postgres:
    image: postgres:latest
    container_name: graze-postgres
    restart: always
    environment:
      POSTGRES_DB: graze
      POSTGRES_USER: graze_user
      POSTGRES_PASSWORD: graze_password
      SCHEMA: graze
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
